# Generated by Django 4.2.7 on 2023-11-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='phoneNo',
            new_name='password',
        ),
    ]
