# Generated by Django 4.2.7 on 2023-11-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummyapp', '0003_member_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField(max_length=20)),
                ('time', models.TimeField(max_length=20)),
                ('people', models.IntegerField(default=0)),
                ('message', models.TextField()),
            ],
        ),
    ]
